### ISSUE TITLE
Problems with Docker

### ISSUE THREAD

**Issue by scharph** [appsflare/pro-ideas#21]
I have problems, getting this running on docker

can you give me some instructions!

Do i have to link a running mongodb container to the pro-ideas container?

**Comment by vjsrinath** [comment]
Can you post the container logs?

If in case you are running mongodb instance within container, then yes you will have to link it.

I would suggest you to create a sanbox instance in https://mlab.com/ and set the **MONGO_URL** environment variable.

**Comment by scharph** [comment]
LOG:

user@debian:~$ docker run -d -p 8082:80 --name idea2 appsflare/pro-ideas
dd1e89c1cc62b115276ab5accfc3b125e6503e0dcbbd031afc19bb1971d84733
user@debian:~$ docker logs idea2
/bin/sh: 1: [node,main.js]: not found

than i ran:

docker run -it -p 127.0.0.1:8081:80 --name pro-ideas2 appsflare/pro-ideas /bin/bash

I looked at the README file in /var/www/bundle:

---------------
This is a Meteor application bundle. It has only one external dependency:
Node.js 0.10.40 or newer. To run the application:

  $ (cd programs/server && npm install)
  $ export MONGO_URL='mongodb://user:password@host:port/databasename'
  $ export ROOT_URL='http://example.com'
  $ export MAIL_URL='smtp://user:password@mailhost:port/'
  $ node main.js

Use the PORT environment variable to set the port where the
application will listen. The default is 80, but that will require
root on most systems.

Find out more about Meteor at meteor.com.

-------------------

OUTPUT from "npm install"

root@15781fa979e0:/var/www/bundle/programs/server# npm install
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/var/www/bundle/programs/server)
root@15781fa979e0:/var/www/bundle/programs/server# 

what is my problem? 

Thank you for your fast reply

**Comment by vjsrinath** [comment]
Please try this
You will have to provide MONGO_URL environment variable
> docker run -MONGO_URL="mongodb://user:password@host:port/databasename" -it -p 127.0.0.1:8081:80 --name pro-ideas2 appsflare/pro-ideas node main.js

**Comment by scharph** [comment]
Thank you but here is my next problem:

i ran:
`docker run -d -e MONGO_URL="mongodb://<mongodb-credentials>" --name pro-ideas3 appsflare/pro-ideas node main.js`

`docker logs` give me:

> WARNING: npm peer requirements (for universe:react-markdown-wysiwyg) not installed:
>  - some of to-markdown,collapse-whitespace,medium-editor,rc-tabs,parse5 are not installed or with problems.
> Kadira: completed instrumenting the app

CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS              PORTS               NAMES
f8962a135adc        appsflare/pro-ideas   "node main.js"      13 minutes ago      Up 13 minutes       **3000/tcp**            pro-ideas3

I opened my Browser and typed 127.0.0.1:**3000**, but nothing happend
Is this the right port?
Do i have to set the port above (-p host:container) or should this work out of the box?
